### PR TITLE
Make binutils build (it is probably not fully functional)

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by jackpot51** [comment]
Why not put this patch into https://github.com/redox-os/binutils-gdb on the Redox branch?

**Comment by jackpot51** [comment]
(Or another branch)

**Comment by ids1024** [comment]
I think it's probably best not to have the hacks with commented out lines when building the cross compiler. It could be a branch of `binutils-gdb` though.

**Comment by jackpot51** [comment]
Yes, I prefer a branch like self_hosting to a patch file

**Comment by ids1024** [comment]
Ok. You can merge redox-os/binutils-gdb#1 into a branch, and I will update this PR.

**Comment by ids1024** [comment]
I've removed the patch; this can now be merged.

**Pull request merged**
